import type { BartTarget } from "../core/types";

export interface BartServerDocument {
  route: string;
  title: string;
  description: string;
  keywords?: string[];
  targets?: BartTarget[];
  /** Markdown body. Server-only; never shipped to the browser. */
  body: string;
}

/** Generated by `bart sync`. Contains markdown bodies, so server-only. */
export interface BartServerManifest {
  documents: BartServerDocument[];
}

export interface ContextBlock {
  route: string;
  title: string;
  body: string;
}

export function tokenize(text: string): string[] {
  return text.toLowerCase().match(/[a-z0-9]+/g) ?? [];
}

function countOccurrences(haystackTokens: string[], term: string): number {
  let count = 0;
  for (const token of haystackTokens) {
    if (token === term) count += 1;
  }
  return count;
}

/**
 * Deterministic lexical score: title and keyword matches weigh most,
 * description next, body term frequency (capped) least.
 */
export function scoreDocument(
  doc: BartServerDocument,
  queryTokens: string[],
): number {
  if (queryTokens.length === 0) return 0;
  const titleTokens = tokenize(doc.title);
  const descriptionTokens = tokenize(doc.description);
  const keywordTokens = (doc.keywords ?? []).flatMap(tokenize);
  const bodyTokens = tokenize(doc.body);

  let score = 0;
  for (const term of new Set(queryTokens)) {
    score += countOccurrences(titleTokens, term) * 4;
    score += countOccurrences(keywordTokens, term) * 3;
    score += countOccurrences(descriptionTokens, term) * 2;
    score += Math.min(countOccurrences(bodyTokens, term), 5);
  }
  return score;
}

export interface SelectedContext {
  blocks: ContextBlock[];
  truncated: boolean;
}

/**
 * Always include the (validated) current page first, then other documents by
 * descending lexical score against the latest user message, under a
 * deterministic character budget with deterministic truncation.
 */
export function selectContext(
  manifest: BartServerManifest,
  currentRoute: string | undefined,
  query: string,
  budgetChars = 40_000,
): SelectedContext {
  const queryTokens = tokenize(query);
  const current = manifest.documents.find((d) => d.route === currentRoute);
  const rest = manifest.documents
    .filter((d) => d !== current)
    .map((doc) => ({ doc, score: scoreDocument(doc, queryTokens) }))
    .filter(({ score }) => score > 0)
    .sort(
      (a, b) => b.score - a.score || a.doc.route.localeCompare(b.doc.route),
    )
    .map(({ doc }) => doc);

  const ordered = current ? [current, ...rest] : rest;

  const blocks: ContextBlock[] = [];
  let used = 0;
  let truncated = false;
  for (const doc of ordered) {
    const remaining = budgetChars - used;
    if (remaining <= 0) {
      truncated = true;
      break;
    }
    let body = doc.body;
    if (body.length > remaining) {
      body = body.slice(0, remaining);
      truncated = true;
    }
    blocks.push({ route: doc.route, title: doc.title, body });
    used += body.length;
  }
  return { blocks, truncated };
}

/**
 * Delimit context so the model treats it as quoted reference data, never as
 * instructions.
 */
export function formatContext(blocks: ContextBlock[]): string {
  if (blocks.length === 0) return "No site content matched this question.";
  return blocks
    .map(
      (block) =>
        `<bart-context route="${block.route}" title="${block.title}">\n${block.body}\n</bart-context>`,
    )
    .join("\n\n");
}
