import type { UIDataTypes, UIMessage } from "ai";

export interface BartTarget {
  id: string;
  description: string;
}

export interface BartRoute {
  route: string;
  title: string;
  description: string;
  targets: BartTarget[];
}

/** Generated by `bart sync`. Safe to ship to the browser: no markdown bodies. */
export interface BartPublicManifest {
  routes: BartRoute[];
}

export type ToolPolicy = "auto" | "confirm" | "disabled";

export interface BartToolPolicies {
  navigate: ToolPolicy;
  highlight: ToolPolicy;
}

export interface NavigateInput {
  route: string;
}

export interface HighlightInput {
  target: string;
}

export interface BartToolOutput {
  ok: boolean;
  reason?: string;
  /** True when the user clicked Allow on the approval card (vs. auto policy). */
  approvedByUser?: boolean;
}

export interface BartTools {
  navigate: { input: NavigateInput; output: BartToolOutput };
  highlight: { input: HighlightInput; output: BartToolOutput };
  [k: string]: { input: unknown; output: unknown };
}

export type BartUIMessage = UIMessage<unknown, UIDataTypes, BartTools>;

export type BartVariant = "dock" | "sidebar" | "spotlight";
